#
# Copyright (c) 2019 Marat Abrarov (abrarov@gmail.com)
#
# Distributed under the MIT License (see accompanying LICENSE)
#

os: windows
language: shell

env:
  global:
    - DOCKER_USER: abrarov

install:
  - powershell -ExecutionPolicy Bypass -File ./install.ps1

script:
  - powershell -ExecutionPolicy Bypass -File ./docker/win-builder/build.ps1 && \
    powershell -ExecutionPolicy Bypass -File ./docker/win-builder/test.ps1

# Disabled due to testing and AppVeyor (which does the same)
#deploy:
#  skip_cleanup: true
#  provider: script
#  script: powershell -ExecutionPolicy Bypass -File .\deploy.ps1
#  on:
#    branch: master
