image: Visual Studio 2017

environment:
  DOCKER_USER:
    secure:
  DOCKER_PASS:
    secure:

install:
  - ps: .\appveyor\install.ps1

build_script:
  - ps: .\appveyor\build.ps1

test_script:
  - ps: .\appveyor\test.ps1

deploy_script:
  - ps: .\appveyor\deploy.ps1
