image: Visual Studio 2017

environment:
  DOCKER_USER: abrarov
  DOCKER_PASS:
    secure: f3DqVP4VKrZqL/5I+s2M7kmMFrG0nINb0qdcamN2GtU=

install:
  - ps: .\install.ps1

build_script:
  - ps: Write-Warning "Skipping due to exhausted quotas"
  #- ps: .\build.ps1

test_script:
  - ps: Write-Host "Skipping due build is disabled"
  #- ps: .\test.ps1

deploy_script:
  - ps: Write-Host "Skipping due build is disabled"
  # - ps: .\deploy.ps1
